#ifndef Random_h
#define Random_h

#include "Arduino.h"
#include "Config.h"

class Random {
  public:
    /**
    * Constructor for the Class.
    * 
    * @param min - Minimum Value for any number generated by this instance
    * @param max - Maximum Value for any number generated by this instance
    **/
    Random(int min, int max);
    /**
     * Generates a random number between the boundaries initialized
     * by the constructor and using a seed read from the Pin
     * from the constructor. It reads a new seed from the 
     * randomPin from the config every tenth call.
     * 
     * @return random number
     */
    int getRandomNumber();
    
  private:
    //Minimum Value for random number generation
    int min;
    //Maximum Value for random number generation
    int max;
    //counter for the life cycle of a seed
    int seedAge;
  
};

#endif